### ISSUE TITLE
TypeError: RNOneSignal.didSetNotificationOpenedHandler is not a function. RN 0.61.5

### ISSUE THREAD

**Issue by Rodrigo77777** [OneSignal/react-native-onesignal#936]
**Description:**
As soon as app opens on Android I get error screen below:

![Screenshot_20200115-144243_Nexudus Passport](https://user-images.githubusercontent.com/26114366/72443023-85ac1400-37a5-11ea-9c21-b4b3ace886ac.jpg)

It seems it's an error that has popped up before in other versions, but it hasn't been reported on the latest one. This happened after updating react-native to 0.61.5 and react-native-onesignal to 3.6.2. I have not yet tested this on iOS.

**Environment**
Using latest version, 3.6.2, installed through npm

**Steps to Reproduce Issue:**
  1. Install the OneSignal SDK using npm into your project
  2. Initialize the SDK on Android
  3. Attempt to receive a push notification

**Comment by Rodrigo77777** [comment]
The issue is specifically caused by the following line:

OneSignal.addEventListener('opened', this.onOpened);

It's impacting both Android and iOS. Code is pretty simple and it has been working for over a year, it stopped working when I updated react-native and this library.

![2020-01-16_16h00_36](https://user-images.githubusercontent.com/26114366/72540840-68487a00-3879-11ea-9396-e5afd8ce3d30.png)
