### ISSUE TITLE
onesignal sends userId null react native

### ISSUE THREAD

**Issue by aniiskywalker** [OneSignal/react-native-onesignal#878]
**Description:**

Hello, I've tried to send some notifications but in every device with iOS 13 onesignal send userId as null, how can I upgrade react native framework without having to upgrade the whole project? I don't want to because it will takes me a lot of time (which I don't have).

**Environment**

` {`
`  "name": "App",`
`  "version": "0.1.0",`
`  "private": true,`
`  "devDependencies": {`
`    "babel-preset-react-native-stage-0": "^1.0.1",`
`    "jest-react-native": "^18.0.0",`
`    "react-test-renderer": "16.2.0"`
`  },`
`  "scripts": {`
`    "start": "react-native start",`
`    "android": "react-native run-android",`
`    "ios": "react-native run-ios",`
`    "test": "node node_modules/jest/bin/jest.js"`
`  },`
`  "jest": {`
`    "preset": "react-native"`
 ` },`
`  "dependencies": {`
`    "moment": "^2.24.0",`
`    "react": "16.2.0",`
`    "react-native": "0.52.0",`
`    "react-native-app-intro-slider": "^0.2.4",`
`    "react-native-button": "^2.3.0",`
`    "react-native-countdown-component": "^2.1.1",`
`    "react-native-elements": "^0.19.0",`
`    "react-native-facebook-login": "^1.6.0",`
`    "react-native-geocoding": "^0.2.0",`
`    "react-native-geolocation-service": "^1.0.2",`
`    "react-native-google-signin": "^0.12.0",`
`    "react-native-image-picker": "^0.26.10",`
`    "react-native-keyboard-manager": "^4.0.13-5",`
`    "react-native-local-storage": "^1.5.2",`
`    "react-native-maps": "^0.20.1",`
`    "react-native-material-bottom-navigation": "^0.9.0",`
`    "react-native-modal": "^6.5.0",`
`    "react-native-modal-dropdown": "^0.6.2",`
`    "react-native-native-video-player": "^1.3.4",`
`    "react-native-navigation": "^1.1.388",`
`    "react-native-onesignal": "^3.2.5",`
`    "react-native-pop-menu": "0.0.9",`
`    "react-native-progress": "^3.5.0",`
`    "react-native-render-html": "^3.9.0",`
`    "react-native-share": "^1.1.0",`
`    "react-native-storage": "^0.2.2",`
`    "react-native-swipe-gestures": "^1.0.2",`
`    "react-native-swipeable-parallax-carousel": "^1.1.0",`
`    "react-native-uuid": "^1.4.9",`
`    "react-native-vector-icons": "^4.5.0",`
`    "react-native-video": "^2.0.0",`
`    "react-native-videoplayer": "^1.2.0"`
`  }`
`}`

**Steps to Reproduce Issue:**

1. Change manually my version of react-native-onesignal and install with `npm install react-native-onesignal`
2. Pod install my updated repo of onesignal
3. Receiving this error below with `OneSignalNotificationServiceExtension `

`  "_OBJC_CLASS_$_WKWebViewConfiguration", referenced from:
      objc-class-ref in libRCTOneSignal.a(OneSignal-arm64-master.o)
  "_OBJC_CLASS_$_WKWebView", referenced from:
      objc-class-ref in libRCTOneSignal.a(OneSignal-arm64-master.o)
  "_CGAffineTransformIdentity", referenced from:
      ___49-[OSInAppMessageViewController animateAppearance]_block_invoke in libRCTOneSignal.a(OneSignal-arm64-master.o)
  "_CGAffineTransformMakeScale", referenced from:
      -[OSInAppMessageViewController addConstraintsForMessage] in libRCTOneSignal.a(OneSignal-arm64-master.o)
ld: symbol(s) not found for architecture arm64
clang: error: linker command failed with exit code 1 (use -v to see invocation)`
. 
There's a better way to update without break all?

**Anything else:**
If somebody has any ideas why I've been received userId as null is welcome, because I don't want to update haha.

**Comment by rgomezp** [comment]
Can you try running `react-native link react-native-onesignal`?

**Comment by smsmdida** [comment]
Same thing on IOS 13.1.2 
it works fine on IOS 13.0

**Comment by aniiskywalker** [comment]
Hello @rgomezp, no, because according to documentation if we use pods we can't link libraries, and I did't link onesignal, Is that causing my problem?

**Comment by rgomezp** [comment]
@aniiskywalker ,
In my experience, the newest version of React Native does not always correctly perform the autolinking step. It doesn't hurt to run the command just to make sure that everything is linked correctly.

**Comment by rgomezp** [comment]
Closing due to no response
