### ISSUE TITLE
Build issue : cannot find symbol import com.onesignal.OneSignal.OSExternalUserIdUpdateCompletionHandler;

### ISSUE THREAD

**Issue by juliusdev** [OneSignal/react-native-onesignal#1014]
**Description:**
Compilation issue with Expo SDK37 and ExpoKit : cannot find symbol OSExternalUserIdUpdateCompletionHandle.

**Environment**
Android API 28
Expo SDK37, and "react-native-onesignal": "^3.7.1"

Segment of app/build.gradle file.
<pre>
buildscript {
  repositories {
      google()
      maven { url 'https://maven.fabric.io/public' }
      maven { url 'https://plugins.gradle.org/m2/' } // Gradle Plugin Portal
  }

  dependencies {
      classpath "gradle.plugin.com.onesignal:onesignal-gradle-plugin:0.12.8"
      classpath 'io.fabric.tools:gradle:1.+'
  }
}
apply plugin: 'com.onesignal.androidsdk.onesignal-gradle-plugin'
apply plugin: 'com.android.application'

....

dependencies { 
    implementation project(':react-native-onesignal')
    implementation fileTree(dir: 'libs', include: ['*.jar'])
    ....
}
</pre>

Here settings.gradle
<pre>
include ':react-native-onesignal'
project(':react-native-onesignal').projectDir = new File(rootProject.projectDir, 	'../node_modules/react-native-onesignal/android')

// Include unimodules.
includeUnimodulesProjects()
</pre>

**Steps to Reproduce Issue:**

1. expo init foo
2. expo eject (ExpoKit)
3. nom install --save react-native-onesignal
4. cd foo/android
5. ./gradlew build

**Anything else:**

<pre>
> Task :react-native-onesignal:compileDebugJavaWithJavac FAILED
/Users/jb/projects/numsync-app/node_modules/react-native-onesignal/android/src/main/java/com/geektime/rnonesignalandroid/RNOneSignal.java:31: error: cannot find symbol
import com.onesignal.OneSignal.OSExternalUserIdUpdateCompletionHandler;
                              ^
  symbol:   class OSExternalUserIdUpdateCompletionHandler
  location: class OneSignal
/Users/jb/projects/numsync-app/node_modules/react-native-onesignal/android/src/main/java/com/geektime/rnonesignalandroid/RNOneSignal.java:380: error: cannot find symbol
      OneSignal.setExternalUserId(externalId, new OneSignal.OSExternalUserIdUpdateCompletionHandler() {
                                                           ^
  symbol:   class OSExternalUserIdUpdateCompletionHandler
  location: class OneSignal
/Users/jb/projects/numsync-app/node_modules/react-native-onesignal/android/src/main/java/com/geektime/rnonesignalandroid/RNOneSignal.java:381: error: method does not override or implement a method from a supertype
         @Override
         ^
/Users/jb/projects/numsync-app/node_modules/react-native-onesignal/android/src/main/java/com/geektime/rnonesignalandroid/RNOneSignal.java:392: error: cannot find symbol
      OneSignal.removeExternalUserId(new OneSignal.OSExternalUserIdUpdateCompletionHandler() {
                                                  ^
  symbol:   class OSExternalUserIdUpdateCompletionHandler
  location: class OneSignal
/Users/jb/projects/numsync-app/node_modules/react-native-onesignal/android/src/main/java/com/geektime/rnonesignalandroid/RNOneSignal.java:393: error: method does not override or implement a method from a supertype
         @Override
         ^
Note: /Users/jb/projects/numsync-app/node_modules/react-native-onesignal/android/src/main/java/com/geektime/rnonesignalandroid/RNOneSignal.java uses or overrides a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
5 errors

</pre>

**Comment by juliusdev** [comment]
It works (compilation ok) after updating onesignal api version to 3.15.0 in the react-native-onesignal build.gradle.
<pre>
dependencies {
    implementation fileTree(include: ['*.jar'], dir: 'libs')
    implementation "com.facebook.react:react-native:${safeExtGet('reactNativeVersion', '+')}"

    // api is used instead of implementation so the parent :app project can access any of the OneSignal Java
    //   classes if needed. Such as com.onesignal.NotificationExtenderService
    api 'com.onesignal:OneSignal:3.15.0'

    testImplementation 'junit:junit:4.12'
}
</pre>

**Comment by rgomezp** [comment]
Howdy,
Yes, please always make sure you are using the most recent version of the SDK. Also, often build issues are resolved by adding the onesignal gradle plugin.

I'm glad you found the solution. Thank you for using OneSignal.

Enjoy!
