### ISSUE TITLE
TypeError: _$$_REQUIRE(_dependencyMap[22], (...)ationWillShowInForegroundHandler is not a function (it is undefined), js engine: hermes

### ISSUE THREAD

**Issue by aneena-thomas** [OneSignal/react-native-onesignal#1657]
### What happened?

Getting error 'TypeError: _$$_REQUIRE(_dependencyMap[22], (...)ationWillShowInForegroundHandler is not a function (it is undefined), js engine: hermes' after updating oneSignal to 5.0.5 in react native 0.73.5

### Steps to reproduce?

```Markdown
Just run the app
```

### What did you expect to happen?

Run the app without error

### React Native OneSignal SDK version

React Native: 0.73.5  oneSignal: 5.0.6

### Which platform(s) are affected?

- [ ] iOS
- [X] Android

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by nan-li** [comment]
Hi @aneena-thomas,
If you upgraded from `v4.x.x` of the react-native-onesignal SDK to `v5.0.5`, this is a major version upgrade with breaking API changes.

The method `notificationWillShowInForegroundHandler` has been removed. It's equivalent is the foreground will display event listener with `OneSignal.Notifications.addEventListener("foregroundWillDisplay", (event) => { ... };)`

Please see the [migration guide](https://github.com/OneSignal/react-native-onesignal/blob/major_release_5.0.0/MIGRATION_GUIDE.md) for all available APIs. It serves as less of a migration guide and more of a glossary of all available APIs on v5.x.x of this SDK.
