### ISSUE TITLE
Cannot compile on RN 0.62

### ISSUE THREAD

**Issue by giladno** [OneSignal/react-native-onesignal#1010]
```
info Running jetifier to migrate libraries to AndroidX. You can disable it using "--no-jetifier" flag.
Jetifier found 1154 file(s) to forward-jetify. Using 12 workers...
info JS server already running.
info Installing the app...

> Task :react-native-onesignal:compileDebugJavaWithJavac FAILED

Deprecated Gradle features were used in this build, making it incompatible with Gradle 7.0.
Use '--warning-mode all' to show the individual deprecation warnings.
See https://docs.gradle.org/6.3/userguide/command_line_interface.html#sec:command_line_warnings
62 actionable tasks: 4 executed, 58 up-to-date
warning: [options] source value 7 is obsolete and will be removed in a future release
warning: [options] target value 7 is obsolete and will be removed in a future release
warning: [options] To suppress warnings about obsolete options, use -Xlint:-options.
/Users/XXX/node_modules/react-native-onesignal/android/src/main/java/com/geektime/rnonesignalandroid/RNOneSignal.java:489: error: unreported exception JSONException; must be caught or declared to be thrown
               callback.invoke(RNUtils.jsonToWritableMap(outcomeEvent.toJSONObject()));
                                                                                  ^
/Users/XXX/node_modules/react-native-onesignal/android/src/main/java/com/geektime/rnonesignalandroid/RNOneSignal.java:502: error: unreported exception JSONException; must be caught or declared to be thrown
               callback.invoke(RNUtils.jsonToWritableMap(outcomeEvent.toJSONObject()));
                                                                                  ^
/Users/XXX/node_modules/react-native-onesignal/android/src/main/java/com/geektime/rnonesignalandroid/RNOneSignal.java:515: error: unreported exception JSONException; must be caught or declared to be thrown
               callback.invoke(RNUtils.jsonToWritableMap(outcomeEvent.toJSONObject()));
                                                                                  ^
Note: /Users/XXX/node_modules/react-native-onesignal/android/src/main/java/com/geektime/rnonesignalandroid/RNOneSignal.java uses or overrides a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
3 errors
3 warnings

FAILURE: Build failed with an exception.
```

**Comment by yadunut** [comment]
Hi there, I'm facing the same issue. How did you resolve this?
Edit: 
Found solution in #1003
