### ISSUE TITLE
Error on start

### ISSUE THREAD

**Issue by theobouwman** [OneSignal/react-native-onesignal#122]
When initializing with this code it throw me `Possible Unhandled Promise Rejection (id: 0):
_this.onError is not a function`.
```
import React, { Component } from 'react'
import {
  AppRegistry,
  StyleSheet,
  Text,
  View
} from 'react-native'

import OneSignal from 'react-native-onesignal'
export default class onesignalApp extends Component {

  componentWillMount() {
    OneSignal.configure({
      onIdsAvailable: function (device) {
        console.log('UserId = ', device.userId);
        console.log('PushToken = ', device.pushToken);
      },
      onNotificationReceived: function (notification) {
        console.log('NOTIFICATION RECEIVED: ', notification);
      },
      onNotificationOpened: function (openResult) {
        console.log('NOTIFICATION OPENED: ', openResult);
        console.log('MESSAGE: ', openResult.notification.payload.body);
        console.log('DATA: ', openResult.notification.payload.additionalData);
        console.log('ISACTIVE: ', openResult.notification.isAppInFocus);
      }
    })
  }

  render() {
    return (
      <View style={styles.container}>

      </View>
    );
  }
}

AppRegistry.registerComponent('onesignalApp', () => onesignalApp);
```
Plz someone help

**Comment by avishayil** [comment]
Not sure this is related to this library.
Can you upload the stack?
Closing this issue in the meanwhile.

**Comment by vedovato** [comment]
Hey. Reopening this cause i'm facing this for a week. It works pretty well "standalone" or, in a brand new project without any other integration. After moving it exactly with same code, versions and stuff, this error occurs. Do you know if there's any conflict with wix react-native-navigation package?

**Comment by parkdcom** [comment]
I got the same issue when I updated from 1.2.1 to 2.0.0. We didn't have this issue before.

W/ReactNativeJS( 6935): Possible Unhandled Promise Rejection (id: 7):
W/ReactNativeJS( 6935): false is not a function (evaluating '_this.onError(args)')

**Comment by avishayil** [comment]
@vedovato @getconcar Can you please share a repo with the problem reproduced?

**Comment by avishayil** [comment]
@vedovato @getconcar Did you sorted the issue?
Generally speaking, This error occurs when you have problems with internet connectivity.
This should be fixed on the https://github.com/geektimecoil/react-native-onesignal/tree/dev branch in the meanwhile.
Can you follow this instructions there?
