### ISSUE TITLE
Android build fails on NotificationExtenderService after upgrading to react-native 0.59.8

### ISSUE THREAD

**Issue by fmonsalvo** [OneSignal/react-native-onesignal#764]
**Description:**
I have an application using react-native-onesignal 3.2.14 which was building just fine. After upgrading to react-native 0.59.8 my android build started failing with issues regarding one signal android classes such as `com.onesignal.OSNotificationReceivedResult`, `com.onesignal.NotificationExtenderService` and `com.onesignal.OSNotificationPayload` as I have implemented a custom notification handler to handle silent notifications as described in one signal documentation.
Suddenly after the upgrade none of these classes are found, and trying to figure out where the error was I found the following line:
`OneSignal Warning: Could not get AGP plugin version`

Looking into one-signal-gradle-plugin I found this issue: https://github.com/OneSignal/OneSignal-Gradle-Plugin/issues/68 which may be related, but I did not change or add any plugin to my build.

(your description here)

**Environment**
 I'm using react-native-onesignal 3.2.14 with react-native 0.59.8, react 16.8.3 via *yarn*.

**Steps to Reproduce Issue:**
1. Install the OneSignal SDK using yarn into my project
2. build using react-native 0.57.0 just fine
3. upgrade to react-native 0.59.8.
4. Execute ./gradlew assembleRelease
5. Build fails since it cannot find the referenced classes, with the AGP warning appearing first.

**Comment by rgomezp** [comment]
Could you please include the specific errors you are seeing with 
> issues regarding one signal android classes such as com.onesignal.OSNotificationReceivedResult, com.onesignal.NotificationExtenderService and com.onesignal.OSNotificationPayload

**Comment by fmonsalvo** [comment]
Hi @rgomezp this is the first warning I see when building for android:
`OneSignal Warning: Could not get AGP plugin version`

Then I get this error:

```/Users/franco/Projects/ironthrone/android/app/src/main/java/com/keenvil/ironthrone/services/KeenvilNotificationExtender.java:4: error: cannot find symbol
import com.onesignal.OSNotificationPayload;
                    ^
  symbol:   class OSNotificationPayload
  location: package com.onesignal
/Users/franco/Projects/ironthrone/android/app/src/main/java/com/keenvil/ironthrone/services/KeenvilNotificationExtender.java:5: error: cannot find symbol
import com.onesignal.NotificationExtenderService;
                    ^
  symbol:   class NotificationExtenderService
  location: package com.onesignal
/Users/franco/Projects/ironthrone/android/app/src/main/java/com/keenvil/ironthrone/services/KeenvilNotificationExtender.java:6: error: cannot find symbol
import com.onesignal.OSNotificationReceivedResult;
                    ^
  symbol:   class OSNotificationReceivedResult
  location: package com.onesignal
/Users/franco/Projects/ironthrone/android/app/src/main/java/com/keenvil/ironthrone/services/KeenvilNotificationExtender.java:11: error: cannot find symbol
public class KeenvilNotificationExtender extends NotificationExtenderService {
                                                 ^
  symbol: class NotificationExtenderService
/Users/franco/Projects/ironthrone/android/app/src/main/java/com/keenvil/ironthrone/services/KeenvilNotificationExtender.java:16: error: cannot find symbol
   protected boolean onNotificationProcessing(OSNotificationReceivedResult receivedResult) {
                                              ^
  symbol:   class OSNotificationReceivedResult
  location: class KeenvilNotificationExtender
/Users/franco/Projects/ironthrone/android/app/src/main/java/com/keenvil/ironthrone/services/KeenvilNotificationExtender.java:15: error: method does not override or implement a method from a supertype
   @Override
   ^
Note: /Users/franco/Projects/ironthrone/android/app/src/main/java/com/keenvil/ironthrone/MainApplication.java uses or overrides a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
6 errors```

**Comment by rgomezp** [comment]
It looks to me like you didn't [link the library](https://documentation.onesignal.com/docs/react-native-sdk-setup#section-link-library-to-project) correctly. Please make sure you didn't skip this important step in the setup

**Comment by Renjithcse** [comment]
Same problem for me. Any solution?

**Comment by rgomezp** [comment]
Have you tried re-linking the library?

**Comment by Renjithcse** [comment]
Yes. I tried relinking and reinstalling the plugin and again linking. None of them worked

**Comment by rgomezp** [comment]
Ok. I will dig further into this. Thanks for your patience

**Comment by emin93** [comment]
Just letting you know I have a similar issue where in my NotificationHandler I get `cannot find symbol import com.onesignal.NotificationExtenderService;`. If I move my NotificationExtender to `node_modules⁩/react-native-onesignal/android⁩/⁨src/main⁩/⁨java⁩/⁨com⁩/⁨geektime⁩/⁨rnonesignalandroid⁩`, it seems to fix the issue. But that's just a workaround and not a permanent solution.

**Comment by mariouzae** [comment]
I'm also facing this same issue.

**Comment by conradjonp** [comment]
any updates? Also having this issue

**Comment by rgomezp** [comment]
Howdy, everyone. We're still working to fix several issues with React Native. Thanks for your patience. We will try to get it out this week

**Comment by conradjonp** [comment]
> Howdy, everyone. We're still working to fix several issues with React Native. Thanks for your patience. We will try to get it out this week

Thanks for the update. In the meantime is there a work around for this? It's blocking our deployment for this week.

**Comment by rgomezp** [comment]
Can you try adding the following:
// react-native.config.js
```
// react-native.config.js
module.exports = {
  dependencies: {
    'react-native-onesignal': {
      platforms: {
        ios: {
          podspecPath: `${__dirname}/node_modules/react-native-onesignal/react-native-onesignal.podspec`,
        },
        android: {
          packageImportPath: 'import com.geektime.rnonesignalandroid.ReactNativeOneSignalPackage;',
          packageInstance: 'new ReactNativeOneSignalPackage()'
        },
      },
    },
  },
};```

**Comment by mariouzae** [comment]
Hi, @rgomezp where this file is located?

**Comment by rgomezp** [comment]
Howdy @mariouzae ,
I should have been more clear. See [this response](https://github.com/geektimecoil/react-native-onesignal/issues/792#issuecomment-511723947) by a member of the OneSignal community

**Comment by Renjithcse** [comment]
Hi @rgomezp i think your solution only applicable for RN 0.60. Onesignal normal push notifications working for me. My problem only with background notifications

**Comment by mariouzae** [comment]
Thank you @rgomezp , I'm trying to implement background notification in RN 0.57, but even creating the file "react-native.config.js" on the top of "react-native-onesignal", I'm getting the error to build the project, it says: 

```
error: cannot find symbol 
import com.onesignal.OSNotificationPayload;
```

**Comment by jpmasud** [comment]
Same issue here with 0.59.8

**Comment by rgomezp** [comment]
Howdy y'all,
We have released a new version of the SDK through npm. Please update and try again. Cheers!

**Comment by Renjithcse** [comment]
Today i updated latest version. Till now i am having same issue 
error: cannot find symbol 
import com.onesignal.OSNotificationPayload;

**Comment by jpmasud** [comment]
Still not working for me

**Comment by conradjonp** [comment]
Not working, error is still producing missing NotificationExtender class.

**Comment by tahasabih** [comment]
It's still not working :(
Please help, I am still stuck on and this is unfortunately preventing us from updating our app on the Play Store.
```
error: cannot find symbol
NotificationExtender
```

**Comment by rgomezp** [comment]
Howdy everyone,
Have you tried upgrading to react-native 0.60.4?

**Comment by conradjonp** [comment]
@rgomezp Yes that is the one we are using

**Comment by tahasabih** [comment]
@rgomezp yes we are also using 0.60.4

**Comment by jkasten2** [comment]
Fixed in PR #824, it will be included in the next release.

**Comment by rochapablo** [comment]
> Fixed in PR #824, it will be included in the next release.

Thanks! 

Working with `"react-native-onesignal": "git+https://git@github.com/geektimecoil/react-native-onesignal.git",`for now.
