### ISSUE TITLE
error: cannot find symbol import com.onesignal.NotificationExtenderService;

### ISSUE THREAD

**Issue by oyesaxena** [OneSignal/react-native-onesignal#1391]
**Description:**

I m upgrading my project from react-native version 0.64.2 to 0.68.0 where we were using oneSignal version 3.9.3 with RN version 0.64.2 which was working properly. We were also using extended notification service and OSNotificationReceivedResult for which we had our own Java file. 
In this java file we wrote our classes which were extending NotificationExtenderService and was using this service during our app launch time. 
Now after upgrading the RN version to 0.68.0, I have tried with 3.9.3 as well as the latest version for react-native-oneSignal i.e. 4.3.9, but I have been facing the same issue in my customised java file for using oneSignal. 
After looking for solutions most people on internet suggested to remove the java file. That will help me achieve the build but my app won't run further after launch. Further looked into the git repo for latest package I guess there were missing files related to the old configurations.

**Environment**

1. OneSignal React-Native version 4.3.9
2. Added in package using yarn
3. RN version 0.68.0
4. React version 17.0.2

**Steps to Reproduce Issue:**

  (write below this line) -->

  1. Install the OneSignal SDK using yarn into your project
  2. Gradle sync works properly
  3. During the build error hits on customised java file for oneSignal .

**Anything else:**

Following part of code is producing the error

`import com.onesignal.NotificationExtenderService;
import com.onesignal.OSNotificationReceivedResult;
import com.onesignal.OneSignal;`

main errors are related to import itself, then wherever we have used the imported class there we are getting errors.
<img width="1420" alt="Screenshot 2022-05-24 at 12 02 01 AM" src="https://user-images.githubusercontent.com/51173629/169884198-0abfd6ac-697e-4b06-ba26-5ff2089b1cc8.png">
<img width="1406" alt="Screenshot 2022-05-24 at 12 03 18 AM" src="https://user-images.githubusercontent.com/51173629/169884371-a2780048-5ad3-4fbb-ad3a-9bcf499e1682.png">

**Comment by jkasten2** [comment]
@oyesaxena Thanks for providing your setup details with your question. The issue is since you updated from OneSignal 3.x.x to 4.x.x there are breaking API changes. Make sure to follow the [OneSignal Step-by-Step React Native 3.x to 4.0.0 Upgrade Guide](https://documentation.onesignal.com/docs/step-by-step-react-native-3x-to-400-upgrade-guide) first to get the main parts of your app updated. Then also make sure to read over [4.0 API Reference - React Native](https://documentation.onesignal.com/docs/react-native-40-api-reference) for any other APIs you might be using.

Lastly for custom `OneSignalCallSerfvice.java` fie, `NotificationExtenderService` also has a breaking API change.  `NotificationExtenderService` is now `OSRemoteNotificationReceivedHandler` and the method `onNotificationProcessing` has been renamed to `remoteNotificationReceived`, along with these methods having different signatures. Check out the new API here:
https://documentation.onesignal.com/docs/40-api-android-native#background-notification-control

**Comment by oyesaxena** [comment]
> @oyesaxena Thanks for providing your setup details with your question. The issue is since you updated from OneSignal 3.x.x to 4.x.x there are breaking API changes. Make sure to follow the [OneSignal Step-by-Step React Native 3.x to 4.0.0 Upgrade Guide](https://documentation.onesignal.com/docs/step-by-step-react-native-3x-to-400-upgrade-guide) first to get the main parts of your app updated. Then also make sure to read over [4.0 API Reference - React Native](https://documentation.onesignal.com/docs/react-native-40-api-reference) for any other APIs you might be using.
> 
> Lastly for custom `OneSignalCallSerfvice.java` fie, `NotificationExtenderService` also has a breaking API change. `NotificationExtenderService` is now `OSRemoteNotificationReceivedHandler` and the method `onNotificationProcessing` has been renamed to `remoteNotificationReceived`, along with these methods having different signatures. Check out the new API here: https://documentation.onesignal.com/docs/40-api-android-native#background-notification-control

thanks for the information and support @jkasten2, your answer helped me to solve most of the issues. Currently in android I m facing issue in stopService() in my custom file that android studio is not able to get the stopService() function and in IOS build the app is crashing at oneSignal.addEventListener() which says that it is an undefined function.
I saw that the function is removed from new update and we will have to handle them one by one. 
Any help for this will be highly helpful as this is the last issue i m facing in my RN upgrade

**Comment by jkasten2** [comment]
> Currently in android I m facing issue in stopService() in my custom file that android studio is not able to get the stopService() function

The `OSRemoteNotificationReceivedHandler` is no longer an Android Service, so `stopService()` is no longer needed.


> IOS build the app is crashing at oneSignal.addEventListener() which says that it is an undefined function.

`OneSignal.addEventListener()` has also been removed, there are now individual functions now, like `OneSignal.setNotificationOpenedHandler()`, `OneSignal.addPermissionObserver()`, etc. The isn't a table of exact mapping of these in the [React Native - 4.0 API Changes](https://documentation.onesignal.com/docs/react-native-40-api-reference) but most are easy to find, but ask if you have any questions.

**Comment by kesheshyan** [comment]
Is this still an issue?

**Comment by kesheshyan** [comment]
Closing for now. Fill free to reopen if the problem persist.
