### ISSUE TITLE
RNOneSignal.configure is not a function after updating OneSignal to the latest version

### ISSUE THREAD

**Issue by Luckygirlllll** [OneSignal/react-native-onesignal#844]
**Description:**
I updated React native OneSignal from 3.2.12 version to 3.3.2 version, after that I started getting error during app launch.

(your description here)

**Environment**

1. react-native: 0.59.8,   "react-native-onesignal": "^3.3.2",
2. I updated OneSignal using npm

**Steps to Reproduce Issue:**

**Anything else:**

(crash stacktraces, as well as any other information here)

Here is my code: 

```
import OneSignal from 'react-native-onesignal';

initialize() {
        OneSignal.init(config.oneSignalAppId, {kOSSettingsKeyAutoPrompt : false});
        OneSignal.inFocusDisplaying(0);

        OneSignal.addEventListener('received', this.onReceived);
        OneSignal.addEventListener('opened', this.onOpened);
        OneSignal.addEventListener('ids', this.onIds);

        OneSignal.configure();
    }
```
Here is the full error stack trace: 

> NOneSignal.configure is not a function. (In 'RNOneSignal.configure()', 'RNOneSignal.configure' is undefined)
> - node_modules/react-native-onesignal/index.js:97:12 in addEventListener
> * src/tracking/PushNotificationService.js:24:35 in initialize
> * src/App.js:37:4 in App
> - node_modules/react-proxy/modules/createClassProxy.js:98:23 in <unknown>
> - node_modules/react-proxy/modules/createClassProxy.js:96:6 in instantiate
>

**Comment by OscarYuen** [comment]
OneSignal.configure() was depreciated at the previous version.
It would be called automatically.

**Comment by Luckygirlllll** [comment]
Hm, weird, but on OneSignal [React Native SDK setup guide](https://documentation.onesignal.com/docs/react-native-sdk-setup) it still says, that we need to use `OneSignal.configure();`

<img width="827" alt="Screen Shot 2019-09-07 at 11 05 59" src="https://user-images.githubusercontent.com/10096433/64471909-9eede580-d15f-11e9-8f22-a11db4d0336f.png">

**Comment by Luckygirlllll** [comment]
When I'm removing OneSignal.configure(); I'm still getting an error: 

> RNOneSignal.configure is not a function

Was` OneSignal.addEventListener('ids', this.onIds) `deprecated a as well?

**Comment by OscarYuen** [comment]
> Hm, weird, but on OneSignal [React Native SDK setup guide](https://documentation.onesignal.com/docs/react-native-sdk-setup) it still says, that we need to use `OneSignal.configure();`
> 
> <img alt="Screen Shot 2019-09-07 at 11 05 59" width="827" src="https://user-images.githubusercontent.com/10096433/64471909-9eede580-d15f-11e9-8f22-a11db4d0336f.png">

I believe the documentation is outdated. At 3.3.1 version, the configure() method was depreciated and at 3.3.2 version it was removed. 

I am not sure about the ids event. It requires some clarification from one-signal.

**Comment by OscarYuen** [comment]
@Luckygirlllll 

[Commit Link](https://github.com/geektimecoil/react-native-onesignal/commit/59925fa67de4a0023701e27b4b7710e6b4e84d38)

As I know from 3.3.1, configure() method would be called automatically from ids event.
And I found this commit for 3.3.2 release. They changed configure() method name in native code.

I am not sure you need to run the pod update and pod install again after updating the onesign version in npm.

**Comment by Luckygirlllll** [comment]
@OscarYuen it seems that in my case error throws` OneSignal.addEventListener('ids', this.onIds);`, if I comment it, app works without error, however, I need this listener, because I use it to get device pushToken  /

**Comment by Luckygirlllll** [comment]
I removed `OneSignal.configure();` from my code  and removed `configure()` from `node_modules/react-native-onesignal/index.js` and app started work normally after that!

**Comment by rgomezp** [comment]
I will make sure the docs get updated. Thanks for bringin this up. The `configure` method is indeed deprecated. You don't need to call this anymore to trigger the 'ids' event as this gets triggered automatically

**Comment by rgomezp** [comment]
The docs have been updated. Cheers

**Comment by luutruong** [comment]
I have same issue. When I upgrade to 3.5.0 and have this:
`RNOneSignal.configure is not a function`

Code:
```
 OneSignal.init(oneSignalAppId, {
        kOSSettingsKeyAutoPrompt: true,
        kOSSettingsKeyInFocusDisplayOption: 0
    });

    OneSignal.addEventListener('received', onReceivedNotification);
    OneSignal.addEventListener('opened', onOpenedNotification);
    OneSignal.addEventListener('ids', onRegisteredIds);
```

I have just install from npm which steps am i missing?

**Comment by rgomezp** [comment]
@luutruong ,
You're definitely on an older version of the SDK. Make sure you updated correctly

**Comment by luutruong** [comment]
@rgomezp  How do i check if my version are latest? I see the Pod output.

```
Installing OneSignal 2.11.2 (was 2.10.0 and source changed to `https://cdn.cocoapods.org/` from `trunk`)
```

Is that latest version?

**Comment by luutruong** [comment]
@rgomezp bump!

**Comment by rgomezp** [comment]
@luutruong ,
Yes, that's the latest iOS native version. But the issue is not on the native side, but rather on the Javascript side. You need to make sure you're using the latest React Native OneSignal SDK version.
Also, please include the entire stack trace, to get a better idea of what is going on

**Comment by luutruong** [comment]
@rgomezp Quite strange. Now it's work fine.

**Comment by rgomezp** [comment]
@luutruong ,
strange. good to hear though! cheers

**Comment by nateblog** [comment]
I had to go through I lot of process just to fix this "ids" issue.

1. when you install the one signal package it is not linked automatically so I had to do it manually via pods:

pod 'react-native-onesignal', :path => '../node_modules/react-native-onesignal/react-native-onesignal.podspec'

then pod install

2. after that I had to locate the OneSignalSDK inside "Pods/OneSignal/iOS_SDK/OneSignalSDK/Framework" folder.

3. Drag "OneSignal.framework" in to my xcode
