### ISSUE TITLE
cannot find symbol import com.onesignal.OneSignal.OutcomeCallback;

### ISSUE THREAD

**Issue by denis-kungurov** [OneSignal/react-native-onesignal#908]
**Description:**

I have an error after updating react-native-onesignal to 3.5.0 from 3.4.1

RNOneSignal.java:31: error: cannot find symbol
import com.onesignal.OneSignal.OutcomeCallback;

**Environment**

**Steps to Reproduce Issue:**

1. Update react-native-onesignal to 3.5.0 from 3.4.1
2. react-native run-android

**Anything else:**

RNOneSignal.java:31: error: cannot find symbol
import com.onesignal.OneSignal.OutcomeCallback;

**Comment by rgomezp** [comment]
Hello,
This means that the OneSignal dependency isn't pulling the latest version of the native Android SDK. Please check that the linking step [worked correctly](https://documentation.onesignal.com/docs/troubleshooting-react-native#section-check-link-step-worked-correctly) and check your gradle to make sure the [latest version](https://github.com/OneSignal/OneSignal-Android-SDK/releases) is being used.

**Comment by denis-kungurov** [comment]
Thanks, it helped. It was 3.12.2 version in onesignal's buld.gradle. After replacing with version 3.12.3 everything works fine
