### ISSUE TITLE
Undefined symbols for architecture x86_64: Symbol: _kOSSettingsKeyAutoPrompt

### ISSUE THREAD

**Issue by Doko-Demo-Doa** [OneSignal/react-native-onesignal#369]
I was using 3.0.7. After upgrading to 3.0.8, I encountered this error.

````

❌  Undefined symbols for architecture x86_64
> Symbol: _kOSSettingsKeyAutoPrompt
> Referenced from: -[AppDelegate application:didFinishLaunchingWithOptions:] in AppDelegate.o



❌  ld: symbol(s) not found for architecture x86_64



❌  clang: error: linker command failed with exit code 1 (use -v to see invocation)


** BUILD FAILED **
````

**Comment by Nightsd01** [comment]
Closing because duplicate of #368, will resolve this today, thank you for reporting it @Doko-Demo-Doa
