### ISSUE TITLE
Build errors with RN 0.57

### ISSUE THREAD

**Issue by hutchy2570** [OneSignal/react-native-onesignal#667]
**Description:**

After upgrading RN to 0.57 I am unable to build the OneSignalNotificationServiceExtension.  This is because of the RN `DevSupport` subSpec.  0.57 introduces an update which uses a`UIApplication.sharedApplication.keyWindow` which isn't allowed in Service Extensions.

https://github.com/facebook/react-native/blob/master/React/DevSupport/RCTDevLoadingView.m#L77

I then tried removing the `DevSupport` subSpec from my podfile, but then I hit an error with undefined symbols.

```
Undefined symbols for architecture x86_64:
  "_OBJC_CLASS_$_RCTDevMenuItem", referenced from:
      objc-class-ref in libReact.common.a(RCTPerfMonitor.o)
  "_OBJC_CLASS_$_RCTInspectorDevServerHelper", referenced from:
      objc-class-ref in libReact.common.a(RCTBridge.o)
      objc-class-ref in libReact.common.a(RCTDevSettings.o)
  "_OBJC_CLASS_$_RCTPackagerConnection", referenced from:
      objc-class-ref in libReact.common.a(RCTDevSettings.o)
  "_OBJC_CLASS_$_RCTDevLoadingView", referenced from:
      objc-class-ref in libReact.common.a(RCTCxxBridge.o)
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
```

I'm unsure if I can disable any more subSpecs without breaking something.  Since the undefined symbols seem to be referenced from the bridge.

**Environment**

RN 0.57
Xcode 10
MacOS 10.14

**Steps to Reproduce Issue:**

This is my Podspec for the service extension.

```
target 'OneSignalNotificationServiceExtension' do

  # Pods for sevice extension
  pod 'React',
    :path => '../node_modules/react-native',
    :inhibit_warnings => true,
    :subspecs => [
      'Core',
      'CxxBridge', # Include this for RN >= 0.47
      'DevSupport', # Include this to enable In-App Devmenu if RN >= 0.43
      'RCTText',
      'RCTNetwork',
      'RCTWebSocket', # needed for debugging
      # Add any other subspecs you want to use in your project
    ]

  # Explicitly include Yoga if you are using RN >= 0.42.0
  pod 'yoga', :path => '../node_modules/react-native/ReactCommon/yoga'

  # Third party deps podspec link
  pod 'DoubleConversion', :podspec => '../node_modules/react-native/third-party-podspecs/DoubleConversion.podspec', :inhibit_warnings => true
  pod 'glog', :podspec => '../node_modules/react-native/third-party-podspecs/glog.podspec', :inhibit_warnings => true
  pod 'Folly', :podspec => '../node_modules/react-native/third-party-podspecs/Folly.podspec', :inhibit_warnings => true

  # pods
  pod 'react-native-onesignal', :path => '../node_modules/react-native-onesignal'

end
```

**Comment by Nightsd01** [comment]
@hutchy2570 The Notification Service Extension is basically an entirely separate executable from your main app. It has no UI. This means you should not be installing all of these react-native pods inside the OneSignalNotificationServiceExtension target.

Take a look at our react-native setup guide, it has specific instructions for how to set up the notification service extension:

https://documentation.onesignal.com/v5.0/docs/react-native-sdk-setup#section-with-cocoapods

**Comment by slorber** [comment]
Hi @Nightsd01 

Actually, some time ago, you recommended to do that in the podfile: https://github.com/geektimecoil/react-native-onesignal/issues/569#issuecomment-404505408

Has the extension integration changed recently and the doc up to date regarding the issue above?

This podfile used to work for me, but on a new RN Expo ejected project this does not work anymore due to `DevSupport` because of `sharedApplication` usage in the extension.

![image](https://user-images.githubusercontent.com/749374/49956566-cb910b80-ff05-11e8-864c-b1cd3a120717.png)

This seems related to this recent RN [commit](https://github.com/facebook/react-native/commit/3d3edfc3da0e92dc5c6c6c3d1ed63a75733a8c5e)
Note that reverting this commit locally does actually make the build pass.
Note that using this `Require Only AppExtension-Safe API = No` workaround didn't work: https://stackoverflow.com/a/34227172/82609

So the podspec @hutchy2570 and me used, used to work but does not work anymore on new RN versions

**Comment by slorber** [comment]
So, I just reverted everything and did the installation again and this time it seems to work a lot better! 

The simple extension pod setup did work and I didn't have to include React dependencies/subspecs

```js
target 'OneSignalNotificationServiceExtension' do
  pod 'OneSignal', '>= 2.9.3', '< 3.0'
end
```

**Comment by slorber** [comment]
@Nightsd01 this would be helpful to add in doc that `libRCTOneSignal.a` does not need to be added when using cocoapods as long as you add the extension to your podfile

![image](https://user-images.githubusercontent.com/749374/49960153-d5b80780-ff0f-11e8-82bb-bc4c2af3e0c0.png)
